### ISSUE TITLE
supports ldap based authentication

### ISSUE THREAD

**Issue by sachinbanugariya** [billchen198318/qifu2#1]
hello,
did this support ldap based authentication?
thanks

**Comment by billchen198318** [comment]
support it,

https://github.com/billchen198318/qifu2/blob/master/core-web/resource/applicationContext/core/README.txt

https://github.com/billchen198318/qifu2/blob/master/core-web/resource/applicationContext/core/applicationContext-shiro-ActiveDirectory-sample.xml
